CREATE SEQUENCE cinema_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE cinema (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE hall (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id BIGINT NOT NULL REFERENCES cinema(id),
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_hall_cinema_name UNIQUE (cinema_id, name)
);

CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    age_rating VARCHAR(255) NOT NULL,
    poster_url VARCHAR(255) NOT NULL,
    release_date DATE NOT NULL
);

CREATE TABLE screening (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movie(id),
    hall_id BIGINT NOT NULL REFERENCES hall(id),
    start_time TIMESTAMP NOT NULL,
    price NUMERIC(10, 2) NOT NULL
);

CREATE TABLE seat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id BIGINT NOT NULL REFERENCES hall(id),
    row_number INTEGER NOT NULL,
    seat_number INTEGER NOT NULL,
    CONSTRAINT uk_seat_hall_row_number UNIQUE (hall_id, row_number, seat_number)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL UNIQUE,
    birth_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE user_secrets (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screening_id BIGINT NOT NULL REFERENCES screening(id),
    seat_id BIGINT NOT NULL REFERENCES seat(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_ticket_screening_seat UNIQUE (screening_id, seat_id)
);
